#!/bin/bash

openocd -s ./openocd \
        -f interface/cmsis-dap.cfg \
	-f apm32f1x.cfg \
	-c init -c "reset halt" \
	-c "set WORKAREASIZE 0x10000" \
	-c "stm32f1x unlock 0" \
	-c "reset halt" \
	-c "flash write_bank 0 bin/gnuk-ST_DONGLE.bin" \
	-c "stm32f1x lock 0" \
	-c "reset halt" \
	-c "exit"
